name: gaussian_splattingv1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.10.12
  - pip=22.0.2
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib